name: tyd
description: Period tracker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  filter_list: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  settings_ui: ^2.0.2
  flutter_colorpicker: ^1.0.3
  collection: ^1.16.0
  stop_watch_timer: ^2.0.0
  swatch_generator: ^0.1.0
  flutter_local_notifications: ^12.0.2
  flutter_native_timezone: ^2.0.0
  timezone: ^0.9.0
  flutter_spinbox: ^0.10.0
  file_picker: ^5.2.2
  share_plus: ^6.0.1
  cross_file: ^0.3.3+2
  path: ^1.8.2
  auto_size_text: ^3.0.0
  scrollable_positioned_list: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  hive_generator: ^1.1.3
  flutter_native_splash: ^2.2.14

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/tyd.png
    - assets/tyd_white.png
    - assets/tyd_android_12.png