name: vula
description: Period tracker.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  calendar_timeline: ^1.0.5
  filter_list: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  settings_ui: ^2.0.2
  flutter_colorpicker: ^1.0.3
  collection: ^1.16.0
  stop_watch_timer: ^2.0.0
  swatch_generator: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  hive_generator: ^1.1.3

flutter:

  uses-material-design: true